version: "3.8"

services:
  blockchain:
    image: lozioo/blockchain:latest
    restart: always

    # Needed for printing logs.
    stdin_open: true  # docker run -i
    tty: true         # docker run -t

    ports:
      - 5080

    environment:
    - HTTP_ADDRESS=0.0.0.0        # str:  IP address where the HTTP server listens for incoming connections.
